### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by hainesm6** [laserson/pytools#2]
Nice collection of tools! However, if you want to permit sharing, shouldn't you assign a `license` to this repository?

**Comment by laserson** [comment]
Yes, though I've basically abandoned this repo. Are you interested in using any bits of code? Could add a license in that case.

**Comment by hainesm6** [comment]
I was considering using one or two elements. In addition, there are currently 5 forks, so I would have thought it would be useful for these users 😊

**Comment by laserson** [comment]
Added the Apache license
